# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0005_auto_20161031_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendsfriend', to='beltexam.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersfriend', to='beltexam.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
